language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database palettepicker_test;' -U postgres
- npm run migrate
deploy:
  provider: heroku
  api_key:
    secure: Qg/IYkz7+COpREkQJu8YoUI5y3hxpos1LU+/rRjn3rG0CfDCxAV2JoYlQ5u+wG2oHW69dDZ5ghqjoRofc0D46BBRG20b3PdNXae3LaI9kP2twwfGr+tF6GzswZ+e+d35U1D918BrbfnHE1JPAEYUlsG0MW+in9x37/x1wkRzb2Sm41Gzq2LmMjXiC62EnoRnMQNv+hyI6OGUP4/H9KCbBhq05b82GK9nupRDEGpV1AySgSqJL/KMvhrhppQ/CUwDipd4LMe03rlCcQq1ONbJCqxCwYAdk5k2wYfqkwTGtAtTQ7n2az0J8nELS5tE7Gx9vmGC4ljd6H0oJxwVSJ0HuGvPzF/eShG+7Yj9lodktypM6yTxGYz1ItdJj7wdSCovK/76hKOXs8ifWH1l1IqY9XlLMQ1umEogniMsM6EIpO5kox21Nfe01aHoidMEVGHris7OFfAIAAXZ1jy1fi6xOJvw8cImo/aT0W+xXufZM8ltp6P5QJPpxTjv4wd8jLSx2sxO1fAIL3dyamCe0C32fccUlyHBvwbEOhNfzZ2Oyomtnuhl9St+yI3huqZtMKgD204W/jg8F+DLAJdGt8dTx8X1C2e6bkCcMiiEnaOkyrDkcH8/Uf6aUTxHCsJQ7/2euPWatzUFKHJC9GRcPAA+yusAzQYTN/AsoxTixAKT8e8=
  app: em-ja-palette-picker-api