language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database palettepicker_test;' -U postgres
- npm run migrate
deploy:
  provider: heroku
  api_key:
    secure: ba0ddfaa-9319-44f9-8f6d-635452f7b5e7
  app: em-ja-palette-picker-api